wrap `#[no_mangle]` in `#[unsafe(no_mangle)]` to resolve error ``` ➜  tmp-rnd git:(main) ✗ cargo build --release -p name-registry    Compiling pvm-contract-macros v0.3.0 (/home/ubuntu/cargo-pvm-contract/crates/pvm-contract-macros)    Compiling name-registry v0.1.0 (/home/ubuntu/tmp-rnd/crates/contracts/main)    Compiling pvm_contract v0.3.0 (/home/ubuntu/cargo-pvm-contract/crates/pvm_contract) error: failed to run custom build command for `name-registry v0.1.0 (/home/ubuntu/tmp-rnd/crates/contracts/main)`
Caused by:
  process didn't exit successfully: `/home/ubuntu/tmp-rnd/target/release/build/name-registry-8242616119d3808c/build-script-build` (exit status: 1)
  --- stderr
  Building PolkaVM binary with profile: Profile { name: "release" }
  PolkaVM build failed: Cargo build failed:
     Compiling pvm-contract-macros v0.3.0 (/home/ubuntu/cargo-pvm-contract/crates/pvm-contract-macros)
     Compiling name-registry v0.1.0 (/home/ubuntu/tmp-rnd/crates/contracts/main)
     Compiling pvm_contract v0.3.0 (/home/ubuntu/cargo-pvm-contract/crates/pvm_contract)
  error: unsafe attribute used without unsafe
    --> crates/contracts/main/src/main.rs:12:1
     |
  12 | #[pvm::contract]
     | ^^^^^^^^^^^^^^^^ usage of unsafe attribute
     |
     = note: this error originates in the attribute macro `pvm::contract` (in Nightly builds, run with -Z macro-backtrace for more info)

  error: could not compile `name-registry` (bin "name-registry") due to 1 previous error
```